CREATE TABLE [dbo].[Account]
(
	[StudentNo] INT NOT NULL CONSTRAINT PK_STUDENT_NO PRIMARY KEY, 
    [Name] VARCHAR(50) NOT NULL, 
    [TeamCode] INT NULL CONSTRAINT FK_TEAM_TEAMCODE FOREIGN KEY REFERENCES Team(TeamCode)
)
